# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\ProjectM\Ui\FormFileUpload.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

from os import getcwd, path as ospath
from sys import path as jppath
jppath.append(getcwd())
from lib.JPPublc import JPPub, JPUser
from lib.JPDatabase.Database import JPDb, JPDbType
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 895)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_Button = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_Button.sizePolicy().hasHeightForWidth())
        self.widget_Button.setSizePolicy(sizePolicy)
        self.widget_Button.setMinimumSize(QtCore.QSize(0, 25))
        self.widget_Button.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget_Button.setSizeIncrement(QtCore.QSize(0, 25))
        self.widget_Button.setBaseSize(QtCore.QSize(0, 25))
        self.widget_Button.setObjectName("widget_Button")
        self.layoutWidget = QtWidgets.QWidget(self.widget_Button)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.Layout_Button = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.Layout_Button.setContentsMargins(0, 0, 0, 0)
        self.Layout_Button.setObjectName("Layout_Button")
        self.verticalLayout_2.addWidget(self.widget_Button)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setMinimumSize(QtCore.QSize(91, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.listAdditional = QtWidgets.QListView(self.layoutWidget1)
        self.listAdditional.setMinimumSize(QtCore.QSize(100, 0))
        self.listAdditional.setObjectName("listAdditional")
        self.gridLayout.addWidget(self.listAdditional, 6, 1, 1, 1)
        self.key_words = QtWidgets.QLineEdit(self.layoutWidget1)
        self.key_words.setMinimumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.key_words.setFont(font)
        self.key_words.setObjectName("key_words")
        self.gridLayout.addWidget(self.key_words, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setMinimumSize(QtCore.QSize(91, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.text = QtWidgets.QTextEdit(self.layoutWidget1)
        self.text.setMinimumSize(QtCore.QSize(100, 0))
        self.text.setObjectName("text")
        self.gridLayout.addWidget(self.text, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setMinimumSize(QtCore.QSize(91, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setMinimumSize(QtCore.QSize(91, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setMinimumSize(QtCore.QSize(91, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.issuing = QtWidgets.QLineEdit(self.layoutWidget1)
        self.issuing.setMinimumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.issuing.setFont(font)
        self.issuing.setObjectName("issuing")
        self.gridLayout.addWidget(self.issuing, 1, 1, 1, 1)
        self.title = QtWidgets.QLineEdit(self.layoutWidget1)
        self.title.setMinimumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setMinimumSize(QtCore.QSize(91, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.issuing_date = QtWidgets.QDateEdit(self.layoutWidget1)
        self.issuing_date.setMinimumSize(QtCore.QSize(50, 25))
        self.issuing_date.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.issuing_date.setFont(font)
        self.issuing_date.setObjectName("issuing_date")
        self.gridLayout.addWidget(self.issuing_date, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setMinimumSize(QtCore.QSize(91, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.describe = QtWidgets.QTextEdit(self.layoutWidget1)
        self.describe.setMinimumSize(QtCore.QSize(0, 0))
        self.describe.setSizeIncrement(QtCore.QSize(0, 100))
        self.describe.setObjectName("describe")
        self.gridLayout.addWidget(self.describe, 4, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 7, 1, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_8.setMinimumSize(QtCore.QSize(91, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.treeWidget = QtWidgets.QTreeWidget(self.layoutWidget2)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.treeWidget)
        self.verticalLayout_2.addWidget(self.splitter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "发文日期："))
        self.label_5.setText(_translate("Form", "说明："))
        self.label_7.setText(_translate("Form", "附件或扫描件："))
        self.label_2.setText(_translate("Form", "发文单位："))
        self.label_6.setText(_translate("Form", "文本内容："))
        self.label_3.setText(_translate("Form", "关键字："))
        self.label_4.setText(_translate("Form", "标题："))
        self.pushButton.setText(_translate("Form", "增加"))
        self.label_8.setText(_translate("Form", "相关项目："))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    db = JPDb()
    db.setDatabaseType(JPDbType.MySQL)


    sys.exit(app.exec_())
