# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\ProjectM\lib\JPDevelopmenter\Ui\FormReportManage.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1086, 757)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        Dialog.setFont(font)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.ReportSelect1 = QtWidgets.QComboBox(self.tab)
        self.ReportSelect1.setMinimumSize(QtCore.QSize(170, 0))
        self.ReportSelect1.setObjectName("ReportSelect1")
        self.horizontalLayout_4.addWidget(self.ReportSelect1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.fX = QtWidgets.QSpinBox(self.tab)
        self.fX.setObjectName("fX")
        self.horizontalLayout_5.addWidget(self.fX)
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.fY = QtWidgets.QSpinBox(self.tab)
        self.fY.setObjectName("fY")
        self.horizontalLayout_5.addWidget(self.fY)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.fWidth = QtWidgets.QSpinBox(self.tab)
        self.fWidth.setObjectName("fWidth")
        self.horizontalLayout_5.addWidget(self.fWidth)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.fHeight = QtWidgets.QSpinBox(self.tab)
        self.fHeight.setObjectName("fHeight")
        self.horizontalLayout_5.addWidget(self.fHeight)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.fReportCopysInfo = QtWidgets.QLineEdit(self.tab)
        self.fReportCopysInfo.setObjectName("fReportCopysInfo")
        self.gridLayout.addWidget(self.fReportCopysInfo, 4, 1, 1, 1)
        self.fItemName = QtWidgets.QLineEdit(self.tab)
        self.fItemName.setObjectName("fItemName")
        self.gridLayout.addWidget(self.fItemName, 0, 1, 1, 1)
        self.fReportPaperOrientation = QtWidgets.QComboBox(self.tab)
        self.fReportPaperOrientation.setObjectName("fReportPaperOrientation")
        self.gridLayout.addWidget(self.fReportPaperOrientation, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.fReportPaperSize = QtWidgets.QComboBox(self.tab)
        self.fReportPaperSize.setObjectName("fReportPaperSize")
        self.gridLayout.addWidget(self.fReportPaperSize, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)
        self.fIsReport = QtWidgets.QCheckBox(self.tab)
        self.fIsReport.setEnabled(True)
        self.fIsReport.setChecked(True)
        self.fIsReport.setObjectName("fIsReport")
        self.gridLayout.addWidget(self.fIsReport, 5, 0, 1, 1)
        self.pk = QtWidgets.QLineEdit(self.tab)
        self.pk.setObjectName("pk")
        self.gridLayout.addWidget(self.pk, 5, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout)
        self.lineEditTongJi = QtWidgets.QLineEdit(self.tab)
        self.lineEditTongJi.setObjectName("lineEditTongJi")
        self.horizontalLayout_6.addWidget(self.lineEditTongJi)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.butAddReport = QtWidgets.QPushButton(self.tab)
        self.butAddReport.setObjectName("butAddReport")
        self.horizontalLayout_3.addWidget(self.butAddReport)
        self.butDeleteReport = QtWidgets.QPushButton(self.tab)
        self.butDeleteReport.setObjectName("butDeleteReport")
        self.horizontalLayout_3.addWidget(self.butDeleteReport)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.butSaveReport = QtWidgets.QPushButton(self.tab)
        self.butSaveReport.setObjectName("butSaveReport")
        self.horizontalLayout_3.addWidget(self.butSaveReport)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.butAddItem = QtWidgets.QPushButton(self.tab)
        self.butAddItem.setObjectName("butAddItem")
        self.horizontalLayout_7.addWidget(self.butAddItem)
        self.butDeleteItem = QtWidgets.QPushButton(self.tab)
        self.butDeleteItem.setObjectName("butDeleteItem")
        self.horizontalLayout_7.addWidget(self.butDeleteItem)
        self.butSaveSubTable = QtWidgets.QPushButton(self.tab)
        self.butSaveSubTable.setObjectName("butSaveSubTable")
        self.horizontalLayout_7.addWidget(self.butSaveSubTable)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(290, 140, 81, 21))
        self.label_2.setStyleSheet("border: 1px groove gray;\n"
"                        /*border-radius: 3px;*/\n"
"                        padding: 2px 4px;\n"
"                        border-width: 1px;\n"
"                        border-style: solid;\n"
"                        background-color: white;\n"
"                        border-color: rgb(171, 171, 171);")
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_3.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "报表选择："))
        self.label_11.setText(_translate("Dialog", "报表名："))
        self.label_8.setText(_translate("Dialog", "纸边距："))
        self.label_5.setText(_translate("Dialog", "上"))
        self.label_6.setText(_translate("Dialog", "下"))
        self.label_7.setText(_translate("Dialog", "左"))
        self.label_4.setText(_translate("Dialog", "右"))
        self.label_9.setText(_translate("Dialog", "纸型："))
        self.label_10.setText(_translate("Dialog", "纸张方向："))
        self.label_12.setText(_translate("Dialog", "联次信息："))
        self.fIsReport.setText(_translate("Dialog", "fIfReport"))
        self.butAddReport.setText(_translate("Dialog", "增加报表"))
        self.butDeleteReport.setText(_translate("Dialog", "删除报表"))
        self.butSaveReport.setText(_translate("Dialog", "保存"))
        self.butAddItem.setText(_translate("Dialog", "增加条目"))
        self.butDeleteItem.setText(_translate("Dialog", "删除条目"))
        self.butSaveSubTable.setText(_translate("Dialog", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "报表"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
        self.label_2.setText(_translate("Dialog", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Page"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
