# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\ProjectM\Ui\FormArchivesEdit.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from lib.JPMvc import JPWidgets as QtWidgets
from PyQt5 import QtCore, QtGui
from os import getcwd
from sys import path as jppath
jppath.append(getcwd())



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1261, 842)
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        Form.setFont(font)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_logo = QtWidgets.QLabel(Form)
        self.label_logo.setMinimumSize(QtCore.QSize(329, 40))
        self.label_logo.setMaximumSize(QtCore.QSize(329, 50))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("../res/gaoke.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.horizontalLayout_2.addWidget(self.label_logo)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setMinimumSize(QtCore.QSize(0, 30))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setMinimumSize(QtCore.QSize(0, 30))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setMinimumSize(QtCore.QSize(0, 25))
        self.label_20.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setMinimumSize(QtCore.QSize(0, 25))
        self.label_7.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.issuing_date = QtWidgets.QDateEdit(Form)
        self.issuing_date.setMinimumSize(QtCore.QSize(90, 25))
        self.issuing_date.setSizeIncrement(QtCore.QSize(0, 25))
        self.issuing_date.setAlignment(QtCore.Qt.AlignCenter)
        self.issuing_date.setCalendarPopup(True)
        self.issuing_date.setObjectName("issuing_date")
        self.gridLayout.addWidget(self.issuing_date, 0, 4, 1, 1)
        self.title = QtWidgets.QLineEdit(Form)
        self.title.setMinimumSize(QtCore.QSize(0, 25))
        self.title.setSizeIncrement(QtCore.QSize(0, 25))
        self.title.setClearButtonEnabled(True)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 4, 2, 1, 5)
        self.key_words = QtWidgets.QLineEdit(Form)
        self.key_words.setMinimumSize(QtCore.QSize(0, 25))
        self.key_words.setSizeIncrement(QtCore.QSize(0, 25))
        self.key_words.setClearButtonEnabled(True)
        self.key_words.setObjectName("key_words")
        self.gridLayout.addWidget(self.key_words, 5, 2, 1, 5)
        self.issuing = QtWidgets.QLineEdit(Form)
        self.issuing.setMinimumSize(QtCore.QSize(0, 25))
        self.issuing.setSizeIncrement(QtCore.QSize(0, 25))
        self.issuing.setClearButtonEnabled(True)
        self.issuing.setObjectName("issuing")
        self.gridLayout.addWidget(self.issuing, 3, 2, 1, 5)
        self.fUserID = QtWidgets.QLineEdit(Form)
        self.fUserID.setMinimumSize(QtCore.QSize(0, 25))
        self.fUserID.setMaximumSize(QtCore.QSize(20, 16777215))
        self.fUserID.setSizeIncrement(QtCore.QSize(0, 25))
        self.fUserID.setReadOnly(True)
        self.fUserID.setClearButtonEnabled(True)
        self.fUserID.setObjectName("fUserID")
        self.gridLayout.addWidget(self.fUserID, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 2, 0, 1, 1)
        self.archive_fulltext = QtWidgets.QTextEdit(Form)
        self.archive_fulltext.setMinimumSize(QtCore.QSize(50, 0))
        self.archive_fulltext.setObjectName("archive_fulltext")
        self.gridLayout.addWidget(self.archive_fulltext, 8, 2, 1, 5)
        self.archives_pk = QtWidgets.QLineEdit(Form)
        self.archives_pk.setMinimumSize(QtCore.QSize(0, 25))
        self.archives_pk.setSizeIncrement(QtCore.QSize(0, 25))
        self.archives_pk.setReadOnly(True)
        self.archives_pk.setClearButtonEnabled(True)
        self.archives_pk.setObjectName("archives_pk")
        self.gridLayout.addWidget(self.archives_pk, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setMinimumSize(QtCore.QSize(0, 25))
        self.label_6.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.archive_type = QtWidgets.QComboBox(Form)
        self.archive_type.setMinimumSize(QtCore.QSize(200, 25))
        self.archive_type.setObjectName("archive_type")
        self.gridLayout.addWidget(self.archive_type, 0, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setMinimumSize(QtCore.QSize(0, 25))
        self.label_5.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.archive_no = QtWidgets.QLineEdit(Form)
        self.archive_no.setMinimumSize(QtCore.QSize(0, 25))
        self.archive_no.setClearButtonEnabled(True)
        self.archive_no.setObjectName("archive_no")
        self.gridLayout.addWidget(self.archive_no, 2, 2, 1, 5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setMinimumSize(QtCore.QSize(500, 0))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_Download = QtWidgets.QPushButton(Form)
        self.btn_Download.setObjectName("btn_Download")
        self.horizontalLayout_3.addWidget(self.btn_Download)
        self.btn_Add = QtWidgets.QPushButton(Form)
        self.btn_Add.setObjectName("btn_Add")
        self.horizontalLayout_3.addWidget(self.btn_Add)
        self.btn_Delete = QtWidgets.QPushButton(Form)
        self.btn_Delete.setObjectName("btn_Delete")
        self.horizontalLayout_3.addWidget(self.btn_Delete)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 7, 9, 1)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 0, 1, 1)
        self.archive_describe = QtWidgets.QTextEdit(Form)
        self.archive_describe.setMinimumSize(QtCore.QSize(50, 0))
        self.archive_describe.setObjectName("archive_describe")
        self.gridLayout.addWidget(self.archive_describe, 7, 2, 1, 5)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setMinimumSize(QtCore.QSize(0, 25))
        self.label_9.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setMinimumSize(QtCore.QSize(0, 25))
        self.label_15.setSizeIncrement(QtCore.QSize(0, 25))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 8, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.is_task_source = QtWidgets.QCheckBox(Form)
        self.is_task_source.setObjectName("is_task_source")
        self.horizontalLayout_4.addWidget(self.is_task_source)
        self.is_formalities = QtWidgets.QCheckBox(Form)
        self.is_formalities.setObjectName("is_formalities")
        self.horizontalLayout_4.addWidget(self.is_formalities)
        self.is_progress = QtWidgets.QCheckBox(Form)
        self.is_progress.setObjectName("is_progress")
        self.horizontalLayout_4.addWidget(self.is_progress)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 2, 1, 5)
        self.label_ProjectLink = QtWidgets.QLabel(Form)
        self.label_ProjectLink.setStyleSheet("border:1px groove gray;border-radius:3px;padding:2px 4px;\n"
"border-width: 1px;border-style: solid;\n"
"background-color: white;\n"
"/*border-color: rgb(255, 170, 0);*/\n"
"\n"
"")
        self.label_ProjectLink.setText("")
        self.label_ProjectLink.setObjectName("label_ProjectLink")
        self.gridLayout.addWidget(self.label_ProjectLink, 6, 2, 1, 5)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Label_Info = QtWidgets.QLabel(Form)
        self.Label_Info.setStyleSheet("color: rgb(255, 0, 0);")
        self.Label_Info.setText("")
        self.Label_Info.setObjectName("Label_Info")
        self.horizontalLayout.addWidget(self.Label_Info)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.butSave = QtWidgets.QPushButton(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../res/ico/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butSave.setIcon(icon)
        self.butSave.setIconSize(QtCore.QSize(16, 16))
        self.butSave.setObjectName("butSave")
        self.horizontalLayout.addWidget(self.butSave)
        self.butCancel = QtWidgets.QPushButton(Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../res/ico/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butCancel.setIcon(icon1)
        self.butCancel.setIconSize(QtCore.QSize(16, 16))
        self.butCancel.setObjectName("butCancel")
        self.horizontalLayout.addWidget(self.butCancel)
        self.but_SelectProject = QtWidgets.QPushButton(Form)
        self.but_SelectProject.setObjectName("but_SelectProject")
        self.horizontalLayout.addWidget(self.but_SelectProject)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.archives_pk, self.issuing)
        Form.setTabOrder(self.issuing, self.title)
        Form.setTabOrder(self.title, self.key_words)
        Form.setTabOrder(self.key_words, self.archive_fulltext)
        Form.setTabOrder(self.archive_fulltext, self.butSave)
        Form.setTabOrder(self.butSave, self.butCancel)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Archives Inoformation"))
        self.label_18.setText(_translate("Form", "档案信息"))
        self.label_19.setText(_translate("Form", "Archives Information"))
        self.label_20.setText(_translate("Form", "关键字:"))
        self.label_7.setText(_translate("Form", "发文单位:"))
        self.label_10.setText(_translate("Form", "文件标题"))
        self.issuing_date.setDisplayFormat(_translate("Form", "yyyy-MM-dd"))
        self.label_16.setText(_translate("Form", "文号:"))
        self.label_6.setText(_translate("Form", "发文日期:"))
        self.label_5.setText(_translate("Form", "文件描述:"))
        self.label_14.setText(_translate("Form", "附件"))
        self.btn_Download.setText(_translate("Form", "下载"))
        self.btn_Add.setText(_translate("Form", "增加"))
        self.btn_Delete.setText(_translate("Form", "删除"))
        self.label_13.setText(_translate("Form", "档案编号:"))
        self.label.setText(_translate("Form", "关联\n"
"项目\n"
"双击添加"))
        self.label_9.setText(_translate("Form", "档案类型:"))
        self.label_15.setText(_translate("Form", "文件全文:"))
        self.is_task_source.setText(_translate("Form", "任务来源文件"))
        self.is_formalities.setText(_translate("Form", "项目手续文件"))
        self.is_progress.setText(_translate("Form", "进度相关文件"))
        self.butSave.setText(_translate("Form", "Save"))
        self.butCancel.setText(_translate("Form", "Cancel"))
        self.but_SelectProject.setText(_translate("Form", "选择项目"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
