# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\ProjectM\Ui\FormProjectInfoEdit.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

from lib.JPMvc import JPWidgets as QtWidgets
from PyQt5 import QtCore, QtGui
from os import getcwd
from sys import path as jppath
jppath.append(getcwd())




class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        Form.setFont(font)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_logo = QtWidgets.QLabel(Form)
        self.label_logo.setMinimumSize(QtCore.QSize(329, 60))
        self.label_logo.setMaximumSize(QtCore.QSize(329, 60))
        self.label_logo.setText("")
        self.label_logo.setPixmap(QtGui.QPixmap("../res/gaoke.png"))
        self.label_logo.setScaledContents(True)
        self.label_logo.setObjectName("label_logo")
        self.horizontalLayout_2.addWidget(self.label_logo)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setMinimumSize(QtCore.QSize(0, 30))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setMinimumSize(QtCore.QSize(0, 30))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setMinimumSize(QtCore.QSize(0, 25))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setMinimumSize(QtCore.QSize(0, 25))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self.state = QtWidgets.QComboBox(Form)
        self.state.setMinimumSize(QtCore.QSize(0, 25))
        self.state.setObjectName("state")
        self.gridLayout.addWidget(self.state, 2, 5, 1, 1)
        self.content = QtWidgets.QTextEdit(Form)
        self.content.setMinimumSize(QtCore.QSize(0, 100))
        self.content.setObjectName("content")
        self.gridLayout.addWidget(self.content, 7, 1, 1, 5)
        self.location = QtWidgets.QLineEdit(Form)
        self.location.setMinimumSize(QtCore.QSize(0, 25))
        self.location.setText("")
        self.location.setObjectName("location")
        self.gridLayout.addWidget(self.location, 1, 3, 1, 3)
        self.org_pk = QtWidgets.QComboBox(Form)
        self.org_pk.setMinimumSize(QtCore.QSize(0, 25))
        self.org_pk.setObjectName("org_pk")
        self.gridLayout.addWidget(self.org_pk, 4, 1, 1, 3)
        self.floorage = QtWidgets.QLineEdit(Form)
        self.floorage.setMinimumSize(QtCore.QSize(0, 25))
        self.floorage.setText("")
        self.floorage.setObjectName("floorage")
        self.gridLayout.addWidget(self.floorage, 0, 5, 1, 1)
        self.project_name = QtWidgets.QLineEdit(Form)
        self.project_name.setMinimumSize(QtCore.QSize(0, 25))
        self.project_name.setObjectName("project_name")
        self.gridLayout.addWidget(self.project_name, 1, 1, 1, 1)
        self.estimated_total_investment = QtWidgets.QLineEdit(Form)
        self.estimated_total_investment.setMinimumSize(QtCore.QSize(0, 25))
        self.estimated_total_investment.setText("")
        self.estimated_total_investment.setObjectName("estimated_total_investment")
        self.gridLayout.addWidget(self.estimated_total_investment, 0, 3, 1, 1)
        self.investor = QtWidgets.QLineEdit(Form)
        self.investor.setMinimumSize(QtCore.QSize(0, 25))
        self.investor.setObjectName("investor")
        self.gridLayout.addWidget(self.investor, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setMinimumSize(QtCore.QSize(0, 25))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 4, 1, 1)
        self.project_simple_name = QtWidgets.QLineEdit(Form)
        self.project_simple_name.setMinimumSize(QtCore.QSize(0, 25))
        self.project_simple_name.setText("")
        self.project_simple_name.setObjectName("project_simple_name")
        self.gridLayout.addWidget(self.project_simple_name, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setMinimumSize(QtCore.QSize(0, 25))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 2, 1, 1)
        self.construction_mode = QtWidgets.QComboBox(Form)
        self.construction_mode.setMinimumSize(QtCore.QSize(0, 25))
        self.construction_mode.setObjectName("construction_mode")
        self.gridLayout.addWidget(self.construction_mode, 3, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setMinimumSize(QtCore.QSize(0, 25))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 4, 0, 1, 1)
        self.key_project_level = QtWidgets.QComboBox(Form)
        self.key_project_level.setMinimumSize(QtCore.QSize(0, 25))
        self.key_project_level.setObjectName("key_project_level")
        self.gridLayout.addWidget(self.key_project_level, 2, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setMinimumSize(QtCore.QSize(0, 25))
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 6, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.land_certificate = QtWidgets.QCheckBox(Form)
        self.land_certificate.setObjectName("land_certificate")
        self.horizontalLayout_3.addWidget(self.land_certificate)
        self.builders_license = QtWidgets.QCheckBox(Form)
        self.builders_license.setObjectName("builders_license")
        self.horizontalLayout_3.addWidget(self.builders_license)
        self.call_for_bids = QtWidgets.QCheckBox(Form)
        self.call_for_bids.setObjectName("call_for_bids")
        self.horizontalLayout_3.addWidget(self.call_for_bids)
        self.gridLayout.addLayout(self.horizontalLayout_3, 6, 1, 1, 3)
        self.commencement = QtWidgets.QDateEdit(Form)
        self.commencement.setMinimumSize(QtCore.QSize(0, 25))
        self.commencement.setCalendarPopup(True)
        self.commencement.setObjectName("commencement")
        self.gridLayout.addWidget(self.commencement, 5, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setMinimumSize(QtCore.QSize(0, 25))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 2, 1, 1)
        self.category = QtWidgets.QComboBox(Form)
        self.category.setMinimumSize(QtCore.QSize(0, 25))
        self.category.setObjectName("category")
        self.gridLayout.addWidget(self.category, 3, 5, 1, 1)
        self.project_pk = QtWidgets.QLineEdit(Form)
        self.project_pk.setEnabled(False)
        self.project_pk.setMinimumSize(QtCore.QSize(0, 25))
        self.project_pk.setText("")
        self.project_pk.setObjectName("project_pk")
        self.gridLayout.addWidget(self.project_pk, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setMinimumSize(QtCore.QSize(0, 25))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setMinimumSize(QtCore.QSize(0, 25))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setMinimumSize(QtCore.QSize(0, 25))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setMinimumSize(QtCore.QSize(0, 25))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setMinimumSize(QtCore.QSize(0, 25))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(0, 25))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setMinimumSize(QtCore.QSize(0, 25))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 4, 1, 1)
        self.approval_date = QtWidgets.QDateEdit(Form)
        self.approval_date.setMinimumSize(QtCore.QSize(0, 25))
        self.approval_date.setCalendarPopup(True)
        self.approval_date.setObjectName("approval_date")
        self.gridLayout.addWidget(self.approval_date, 4, 5, 1, 1)
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setMinimumSize(QtCore.QSize(0, 25))
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 4, 4, 1, 1)
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setMinimumSize(QtCore.QSize(0, 25))
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 5, 0, 1, 1)
        self.required_commencement = QtWidgets.QDateEdit(Form)
        self.required_commencement.setMinimumSize(QtCore.QSize(0, 25))
        self.required_commencement.setCalendarPopup(True)
        self.required_commencement.setObjectName("required_commencement")
        self.gridLayout.addWidget(self.required_commencement, 5, 1, 1, 1)
        self.completion_date = QtWidgets.QDateEdit(Form)
        self.completion_date.setMinimumSize(QtCore.QSize(0, 25))
        self.completion_date.setCalendarPopup(True)
        self.completion_date.setObjectName("completion_date")
        self.gridLayout.addWidget(self.completion_date, 6, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setMinimumSize(QtCore.QSize(0, 25))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 6, 4, 1, 1)
        self.required_completion_date = QtWidgets.QDateEdit(Form)
        self.required_completion_date.setMinimumSize(QtCore.QSize(0, 25))
        self.required_completion_date.setCalendarPopup(True)
        self.required_completion_date.setObjectName("required_completion_date")
        self.gridLayout.addWidget(self.required_completion_date, 5, 5, 1, 1)
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setMinimumSize(QtCore.QSize(0, 25))
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 5, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.butSave = QtWidgets.QPushButton(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../res/ico/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butSave.setIcon(icon)
        self.butSave.setIconSize(QtCore.QSize(16, 16))
        self.butSave.setObjectName("butSave")
        self.horizontalLayout.addWidget(self.butSave)
        self.butCancel = QtWidgets.QPushButton(Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../res/ico/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butCancel.setIcon(icon1)
        self.butCancel.setIconSize(QtCore.QSize(16, 16))
        self.butCancel.setObjectName("butCancel")
        self.horizontalLayout.addWidget(self.butCancel)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        self.butCancel.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "User Information"))
        self.label_18.setText(_translate("Form", "项目信息"))
        self.label_19.setText(_translate("Form", "Project Information"))
        self.label.setText(_translate("Form", "项目名称："))
        self.label_7.setText(_translate("Form", "建设投资模式："))
        self.label_10.setText(_translate("Form", "建设内容："))
        self.label_4.setText(_translate("Form", "状态："))
        self.label_5.setText(_translate("Form", "位置："))
        self.label_16.setText(_translate("Form", "归属单位："))
        self.label_14.setText(_translate("Form", "手续："))
        self.land_certificate.setText(_translate("Form", "土地证"))
        self.builders_license.setText(_translate("Form", "施工许可证"))
        self.call_for_bids.setText(_translate("Form", "招标"))
        self.commencement.setDisplayFormat(_translate("Form", "yyyy-M-d"))
        self.label_12.setText(_translate("Form", "实际开工日期："))
        self.label_9.setText(_translate("Form", "总投资额(万元)："))
        self.label_15.setText(_translate("Form", "项目编号："))
        self.label_6.setText(_translate("Form", "重点项目级别："))
        self.label_2.setText(_translate("Form", "标准简称："))
        self.label_11.setText(_translate("Form", "建筑面积(平米)："))
        self.label_3.setText(_translate("Form", "投资人："))
        self.label_8.setText(_translate("Form", "项目类别："))
        self.approval_date.setDisplayFormat(_translate("Form", "yyyy-M-d"))
        self.label_20.setText(_translate("Form", "立项日期："))
        self.label_21.setText(_translate("Form", "任务要求开工日期："))
        self.required_commencement.setDisplayFormat(_translate("Form", "yyyy-M-d"))
        self.completion_date.setDisplayFormat(_translate("Form", "yyyy-M-d"))
        self.label_13.setText(_translate("Form", "实际完工日期："))
        self.required_completion_date.setDisplayFormat(_translate("Form", "yyyy-M-d"))
        self.label_17.setText(_translate("Form", "任务要求完成日期："))
        self.butSave.setText(_translate("Form", "Save"))
        self.butCancel.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
